version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
         - "80:4000"
    environment:
      - APP_ENV=production
      - APP_KEY=base64:SBBig6vneOytrjug5CliWTC1pPPRhzBTTOLtlbnhhys=
      - APP_DEBUG=true
      - APP_URL=https://surigao-health.onrender.com
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-ct05f768ii6s73fhjan0-a
      - DB_PORT=5432
      - DB_DATABASE=surigao_health
      - DB_USERNAME=surigao_health_user
      - DB_PASSWORD=Bv18A1HWIXJMuASL5s23yYJ3oMM3cV6p
    volumes:
      - .:/var/www/html
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
