version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
         - "80:4000"
    environment:
      - APP_ENV=production
      - APP_KEY=base64:SBBig6vneOytrjug5CliWTC1pPPRhzBTTOLtlbnhhys=
      - APP_DEBUG=false
      - APP_URL=https://surigao-health.onrender.com
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-ct24ill6l47c73bk71og-a
      - DB_PORT=5432
      - DB_DATABASE=cortel
      - DB_USERNAME=cortel_user
      - DB_PASSWORD=A8jPq6qlwzFMXF81we3E5Cjolvw5cjK7
    volumes:
      - .:/var/www/html
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
